### ISSUE TITLE
DOCUMENTATION.md dosyası codebase ile çelişiyor

### ISSUE THREAD

**Issue by lumosmind** [workincart/frontend-task#4]
[şu adımda](https://github.com/workincart/frontend-task/blob/main/DOCUMENTATION.md#api-nestjs-graphql) bahsedilen 
`api/graphql` klasörü repoda yok. Bu yüzden hata alıyorum kurulum aşamasında.

**Comment by tekintopuz** [comment]
buna ihtiyacın yok. Restful üzerinden ilerlemen gerekiyor.

**Comment by lumosmind** [comment]
Teşekkürler projeyi çalıştırdım
